services:
  - type: web
    name: Period-Tracker
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
